export const models = {
   users: {
      lid: null,
      afk: -1,
      afkReason: '',
      afkObj: {},
      banned: false,
      ban_temporary: 0,
      ban_times: 0,
      premium: false,
      expired: 0,
      lastseen: 0,
      hit: 0,
      warning: 0,
      example: []
   },
   groups: {
      activity: 0,
      antidelete: false,
      antilink: false,
      antivirtex: false,
      antitagsw: true,
      filter: false,
      left: false,
      localonly: false,
      mute: false,
      viewonce: false,
      autosticker: false,
      member: {},
      text_left: '',
      text_welcome: '',
      welcome: false,
      expired: 0,
      stay: false
   },
   chats: {
      chat: 0,
      lastchat: 0,
      lastseen: 0
   },
   setting: {
      autobackup: true,
      autodownload: true,
      antispam: false,
      debug: false,
      notifier: true,
      error: [],
      hidden: [],
      pluginDisable: [],
      receiver: [],
      groupmode: false,
      sk_pack: '© BagusXd',
      sk_author: 'Created by Bagus',
      self: false,
      noprefix: false,
      multiprefix: false,
      prefix: ['.', '#', '!', '/'],
      toxic: [""],
      online: true,
      onlyprefix: '/',
      owners: ['6281779469215'],
      lastReset: new Date * 1,
      msg: 'Hi +tag 🪸\nI am an automated system (WhatsApp Bot) that can help to do something, search and get data / information only through WhatsApp.\n\n◦ *Module* : +module\n◦ *Database* : +db\n◦ *Library* : Baileys +version\n◦\n\nIf you find an error plan contact the owner.',
      style: 4,
      cover: 'https://imgkub.com/images/2025/09/24/image0fe254c6cbb0910a.jpg',
      link: ''
   }
}
